Neighborhood.create(:name => "TestNeighborhoodA")
Neighborhood.create(:name => "TestNeighborhoodB")
Neighborhood.create(:name => "TestNeighborhoodC")
Restaurant.create(:name => "TestRest1", :grade => 'A', :zip => 00001, :neighborhood_id => 1, :cuisine => "garbage")
Restaurant.create(:name => "TestRest2", :grade => 'B', :zip => 00002, :neighborhood_id => 1, :cuisine => "refuse")
Restaurant.create(:name => "TestRest3", :grade => 'C', :zip => 00003, :neighborhood_id => 2, :cuisine => "trash")
Restaurant.create(:name => "TestRest4", :grade => 'pending', :zip => 00004, :neighborhood_id => 3, :cuisine => "detritus")
