Neighborhood.create(:name => "TestNeighborhoodA")
Neighborhood.create(:name => "TestNeighborhoodB")
Neighborhood.create(:name => "TestNeighborhoodC")

Restaurant.create(:name => "TestRest1", :grade => 'A', :zip => 00001, :neighborhood_id => 1, :cuisine => "garbage")
Restaurant.create(:name => "TestRest2", :grade => 'B', :zip => 00002, :neighborhood_id => 1, :cuisine => "refuse")
Restaurant.create(:name => "TestRest3", :grade => 'C', :zip => 00003, :neighborhood_id => 2, :cuisine => "trash")
Restaurant.create(:name => "TestRest4", :grade => 'pending', :zip => 00004, :neighborhood_id => 3, :cuisine => "detritus")
Restaurant.create(:name => "TestRest5", :grade => 'A', :zip => 00001, :neighborhood_id => 3, :cuisine => "garbage")
Restaurant.create(:name => "TestRest6", :grade => 'B', :zip => 00002, :neighborhood_id => 3, :cuisine => "refuse")
Restaurant.create(:name => "TestRest7", :grade => 'C', :zip => 00003, :neighborhood_id => 3, :cuisine => "trash")
Restaurant.create(:name => "TestRest8", :grade => 'pending', :zip => 00004, :neighborhood_id => 3, :cuisine => "detritus")
Restaurant.create(:name => "TestRest9", :grade => 'A', :zip => 00001, :neighborhood_id => 1, :cuisine => "garbage")
Restaurant.create(:name => "TestRest10", :grade => 'B', :zip => 00002, :neighborhood_id => 1, :cuisine => "refuse")
Restaurant.create(:name => "TestRest11", :grade => 'C', :zip => 00003, :neighborhood_id => 3, :cuisine => "trash")
Restaurant.create(:name => "TestRest12", :grade => 'pending', :zip => 00004, :neighborhood_id => 3, :cuisine => "detritus")
Restaurant.create(:name => "TestRest13", :grade => 'A', :zip => 00001, :neighborhood_id => 2, :cuisine => "garbage")
Restaurant.create(:name => "TestRest14", :grade => 'B', :zip => 00002, :neighborhood_id => 2, :cuisine => "refuse")
Restaurant.create(:name => "TestRest15", :grade => 'C', :zip => 00003, :neighborhood_id => 2, :cuisine => "trash")
Restaurant.create(:name => "TestRest16", :grade => 'pending', :zip => 00004, :neighborhood_id => 3, :cuisine => "detritus")
